[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-traits"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.1.0"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.1"
gimli = "0.15.0"
parity-wasm = "0.28.0"
twiggy-ir = { version = "0.1.0", path = "../ir" }
csv = "1.0.0-beta.5"
regex = "1.0.0"
